use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=AGENTOS_BUILD_CHANNEL");
    let channel = std::env::var("AGENTOS_BUILD_CHANNEL").unwrap_or_else(|_| "dev".to_string());
    match channel.as_str() {
        "release" | "dev" => {}
        other => panic!("AGENTOS_BUILD_CHANNEL must be `release` or `dev`, got `{other}`"),
    }
    println!("cargo:rustc-env=AGENTOS_BUILD_CHANNEL={channel}");

    embed_result_schemas();
}

/// Embed every committed CLI result JSON Schema (issue #634) into the binary so a
/// released `agentos` ships its schemas and can print them on demand
/// (`agentos schema-index [NAME]`) with no source checkout. The generated table
/// is `(short_name, filename, contents)` rows plus the index; it is derived from
/// whatever `.schema.json` files sit in `cli/schema/`, so adding a schema needs
/// no edit here. The inventory contract test keeps that directory in lockstep
/// with the source's result families.
fn embed_result_schemas() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let schema_dir = Path::new(&manifest_dir).join("schema");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("schemas_embedded.rs");

    // Re-run if any schema file (or the directory listing) changes.
    println!("cargo:rerun-if-changed={}", schema_dir.display());

    let mut files: Vec<String> = std::fs::read_dir(&schema_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", schema_dir.display()))
        .filter_map(|entry| {
            entry
                .ok()
                .map(|e| e.file_name().to_string_lossy().into_owned())
        })
        .filter(|name| name.ends_with(".schema.json"))
        .collect();
    files.sort();

    let mut generated = String::new();
    generated.push_str(
        "// @generated by build.rs: the committed CLI result schemas, embedded (#634).\n\
         /// The schema inventory index (`cli/schema/index.json`), embedded.\n",
    );
    let index_path = schema_dir.join("index.json");
    println!("cargo:rerun-if-changed={}", index_path.display());
    writeln!(
        generated,
        "pub static SCHEMA_INDEX: &str = include_str!({:?});",
        index_path.display().to_string()
    )
    .unwrap();

    generated.push_str(
        "/// Every embedded result schema as `(short_name, file_name, contents)`,\n\
         /// sorted by file name. `short_name` drops the `.schema.json` suffix.\n\
         pub static SCHEMAS: &[(&str, &str, &str)] = &[\n",
    );
    for file in &files {
        let short = file.trim_end_matches(".schema.json");
        let path = schema_dir.join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(
            generated,
            "    ({short:?}, {file:?}, include_str!({:?})),",
            path.display().to_string()
        )
        .unwrap();
    }
    generated.push_str("];\n");

    std::fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}
